{{ if .Values.redis.master.create }}
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "guestbook.name" . }}-redis-master
  labels:
    app: redis
    {{- include "guestbook.labels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      app: redis
      role: master
      tier: backend
  replicas: {{ .Values.redis.master.replicaCount}}
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: {{ .Values.redis.master.image }}
        {{- if .Values.redis.master.createResources }}
        {{- with .Values.redis.master.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.redis.master.containerPort }}
{{ end }}